export const DOCUMENT_CHECKLIST: string[] = [
    "RG e CPF (ou CNH)",
    "Comprovante de Residência (recente)",
    "Contrato Social (se pessoa jurídica)",
    "Notas Fiscais de produtos ou serviços",
    "Recibos de pagamento",
    "Orçamentos",
    "Contrato assinado entre as partes",
    "Boletos e comprovantes de pagamento",
    "Faturas de cartão de crédito",
    "Extratos bancários",
    "Prints de conversas (WhatsApp, E-mail)",
    "Protocolos de atendimento",
    "Certidão de Casamento/Nascimento",
    "Documentos do veículo (CRLV)",
    "Boletim de Ocorrência",
    "Laudos e exames médicos",
    "Receitas médicas",
    "Termo de Garantia",
    "Fotos e vídeos",
    "Cartas de cobrança ou notificação",
    "Procuração (se aplicável)",
    "Declaração de Pobreza (para Justiça Gratuita)",
    "Nome e endereço de testemunhas (até 3)",
    "CNPJ da empresa reclamada",
    "Outros documentos relevantes"
];
